version: '2.4'

services:
  db:
    image: postgres:14
    container_name: chatbot_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatbot_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
